### ISSUE TITLE
Gang Garrison 2 is not on Steam (Greenlight)

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#19]
See: www.ganggarrison.com/forums/index.php?topic=35477.0

**Comment by harmjanhaisma** [comment]
i don't think an open source game is allowed on steam.

**Comment by arctic5** [comment]
it is

**Comment by harmjanhaisma** [comment]
oh good!

**Comment by harmjanhaisma** [comment]
i keep getting this error on win 10 when running git -> gmk 
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Loading lib files in C:\Users\harm-jan\Desktop\gg2\Gang-Garrison-2\Source\gmksplit.jar
01_move.lgl 02_main1.lgl 03_main2.lgl 04_control.lgl
 05_score.lgl 06_extra.lgl 07_draw.lgl
Exception in thread "main" java.io.IOException: Resource group directory: Haxxy Statues not found!
        at com.ganggarrison.gmdec.ResourceReader$SubtreeReader.readSubtree(ResourceReader.java:119)
        at com.ganggarrison.gmdec.ResourceReader$SubtreeReader.readSubtree(ResourceReader.java:121)
        at com.ganggarrison.gmdec.ResourceReader.readTree(ResourceReader.java:65)
        at com.ganggarrison.gmdec.GmkSplitter.compose(GmkSplitter.java:128)
        at com.ganggarrison.gmdec.GmkSplitter.main(GmkSplitter.java:76)

**Comment by cher-nov** [comment]
> Seeing as Steam Greenlight no longer exists this issue can be closed.

There's Steam Direct now tho.
